version: "3.1"
services:

    php-apache:
      build: docker/php-apache
      container_name: faberlic-php-apache
      working_dir: /var/www/html
      tty: true
      volumes:
        - .:/var/www/html
        - ./docker/php-apache/apache2.conf:/etc/apache2/apache2.conf
        - ./docker/php-apache/php5.load:/etc/apache2/mods-available/php5.load
        - ./docker/php-apache/php.ini:/root/.phpbrew/php/php-5.3.29/etc/php.ini
        - ./docker/php-apache/oci8.ini:/usr/share/php5/common/oci8.ini
        - ./docker/php-apache/tnsnames.ora:/opt/oracle/instantclient_12_2/sdk/admin/tnsnames.ora
        - ./docker/php:/usr/local/etc/php/custom.d
      ports:
        - "80:80"
        - "443:443"

    memcached:
      image: memcached:latest
      ports:
        - 11211:11211
      command:
        - '--memory-limit=1024'   
